name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: windows
            goarch: amd64
            ext: ".exe"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          APP_NAME=$(basename "$GITHUB_REPOSITORY")

          mkdir -p dist

          go build \
            -trimpath \
            -ldflags="-s -w" \
            -o "dist/${APP_NAME}-${GITHUB_REF_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}" \
            .

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*
          generate_release_notes: true
